from flask_batteries_included.sqldb import ModelIdentifier, db
from sqlalchemy.orm import column_property


class AggObservationSets(ModelIdentifier, db.Model):
    record_day = db.Column(db.String(), nullable=False)
    location_id = db.Column(db.String(), nullable=False)
    score_severity = db.Column(db.String(), nullable=False)
    all_obs_sets = db.Column(db.Integer().evaluates_none(), nullable=False)
    late_obs_sets = db.Column(db.Integer().evaluates_none(), nullable=False)
    missing_obs = db.Column(db.Integer().evaluates_none(), nullable=False)
    o2_therapy_status = db.Column(db.Integer().evaluates_none(), nullable=False)
    heart_rate = db.Column(db.Integer().evaluates_none(), nullable=False)
    spo2 = db.Column(db.Integer().evaluates_none(), nullable=False)
    temperature = db.Column(db.Integer().evaluates_none(), nullable=False)
    diastolic_blood_pressure = db.Column(db.Integer().evaluates_none(), nullable=False)
    respiratory_rate = db.Column(db.Integer().evaluates_none(), nullable=False)
    consciousness_acvpu = db.Column(db.Integer().evaluates_none(), nullable=False)
    systolic_blood_pressure = db.Column(db.Integer().evaluates_none(), nullable=False)
    nurse_concern = db.Column(db.Integer().evaluates_none(), nullable=False)
    minus60 = db.Column(db.Integer().evaluates_none(), nullable=False)
    minus45_59 = db.Column(db.Integer().evaluates_none(), nullable=False)
    minus30_44 = db.Column(db.Integer().evaluates_none(), nullable=False)
    minus15_29 = db.Column(db.Integer().evaluates_none(), nullable=False)
    minus0_14 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus1_15 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus16_30 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus31_45 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus46_60 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus61_75 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus76_90 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus91_105 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus106_120 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus121_135 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus136_150 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus151_165 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus166_180 = db.Column(db.Integer().evaluates_none(), nullable=False)
    plus180 = db.Column(db.Integer().evaluates_none(), nullable=False)
    on_time = column_property(all_obs_sets - late_obs_sets)
