"""add indexes

Revision ID: 7c044c108b2f
Revises: ecac6f01a4fc
Create Date: 2020-11-05 16:11:53.371980

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c044c108b2f"
down_revision = "ecac6f01a4fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_observation_observation_set_uuid"),
        "observation",
        ["observation_set_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observation_observation_set_uuid"), table_name="observation")
    # ### end Alembic commands ###
