"""Added patient_id

Revision ID: e6b64a79cd53
Revises: 91e25778425d
Create Date: 2020-03-26 11:00:10.011841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6b64a79cd53"
down_revision = "91e25778425d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "observation", ["uuid"])
    op.create_unique_constraint(None, "observation_meta_data", ["uuid"])
    op.add_column(
        "observation_set", sa.Column("patient_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_observation_set_patient_id"),
        "observation_set",
        ["patient_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "observation_set", ["uuid"])
    op.alter_column(
        "observation_set",
        "encounter_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "observation_set", type_="unique")
    op.drop_index(op.f("ix_observation_set_patient_id"), table_name="observation_set")
    op.drop_column("observation_set", "patient_id")
    op.drop_constraint(None, "observation_meta_data", type_="unique")
    op.drop_constraint(None, "observation", type_="unique")
    op.alter_column(
        "observation_set",
        "encounter_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=False,
    )
    # ### end Alembic commands ###
