"""Index by encounter_id and record_time

Revision ID: ecac6f01a4fc
Revises: e6b64a79cd53
Create Date: 2020-07-30 17:32:46.005711

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecac6f01a4fc"
down_revision = "e6b64a79cd53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "encounter_record_time",
        "observation_set",
        ["encounter_id", sa.text("record_time DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("encounter_record_time", table_name="observation_set")
    # ### end Alembic commands ###
