@startuml

skinparam defaultFontName Courier

Class Observation {
    VARCHAR[36]                 ★ uuid                               
    VARCHAR                     ☆ observation_set_uuid               
    DATETIME                    ⚪ created                            
    VARCHAR                     ⚪ created_by_                        
    DATETIME                    ⚪ measured_time                      
    DATETIME                    ⚪ modified                           
    VARCHAR                     ⚪ modified_by_                       
    VARCHAR                     ⚪ observation_string                 
    VARCHAR                     ⚪ observation_type                   
    VARCHAR                     ⚪ observation_unit                   
    FLOAT                       ⚪ observation_value                  
    BOOLEAN                     ⚪ patient_refused                    
    INTEGER                     ⚪ score_value                        
    +                           observation_metadata                 
    on_patch()                                                       
    to_dict()                                                        
    to_map_dict()                                                    
    INDEX[observation_set_uuid] » ix_observation_observation_set_uuid
    INDEX[observation_type]     » ix_observation_observation_type    
}

Class ObservationSet {
    VARCHAR[36]                     ★ uuid                           
    DATETIME                        ⚪ created                        
    VARCHAR                         ⚪ created_by_                    
    BOOLEAN                         ⚪ empty_set                      
    VARCHAR[36]                     ⚪ encounter_id                   
    BOOLEAN                         ⚪ is_partial                     
    VARCHAR[36]                     ⚪ location                       
    INTEGER                         ⚪ mins_late                      
    DATETIME                        ⚪ modified                       
    VARCHAR                         ⚪ modified_by_                   
    VARCHAR                         ⚪ monitoring_instruction         
    VARCHAR                         ⚪ obx_abnormal_flags             
    VARCHAR                         ⚪ obx_reference_range            
    VARCHAR[36]                     ⚪ patient_id                     
    VARCHAR                         ⚪ ranking                        
    DATETIME                        ⚪ record_time                    
    VARCHAR                         ⚪ score_severity                 
    VARCHAR                         ⚪ score_string                   
    VARCHAR                         ⚪ score_system                   
    INTEGER                         ⚪ score_value                    
    INTEGER                         ⚪ spo2_scale                     
    DATETIME                        ⚪ time_next_obs_set_due          
    +                               observations                     
    on_patch()                                                       
    to_dict()                                                        
    to_map_dict()                                                    
    INDEX[encounter_id,record_time] » encounter_record_time          
    INDEX[encounter_id]             » ix_observation_set_encounter_id
    INDEX[patient_id]               » ix_observation_set_patient_id  
}

Class ObservationMetaData {
    VARCHAR[36]   ★ uuid                  
    VARCHAR       ☆ observation_uuid      
    DATETIME      ⚪ created               
    VARCHAR       ⚪ created_by_           
    INTEGER       ⚪ gcs_eyes              
    VARCHAR       ⚪ gcs_eyes_description  
    INTEGER       ⚪ gcs_motor             
    VARCHAR       ⚪ gcs_motor_description 
    INTEGER       ⚪ gcs_verbal            
    VARCHAR       ⚪ gcs_verbal_description
    VARCHAR       ⚪ mask                  
    INTEGER       ⚪ mask_percent          
    DATETIME      ⚪ modified              
    VARCHAR       ⚪ modified_by_          
    VARCHAR       ⚪ patient_position      
    to_dict()                             
    to_map_dict()                         
}

Observation <--o ObservationSet: observation_set_uuid

ObservationMetaData <--o Observation: observation_uuid

right footer generated by sadisplay v0.4.9

@enduml
